const { chromium } = require('playwright');
const fs=require('fs'); const path=require('path'); const assert=require('assert');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {channel:'chrome'}),headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:800},deviceScaleFactor:2});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const popup=fs.readFileSync(path.join(root,'popup.html'),'utf8').replace('<link rel="stylesheet" href="popup.css">',`<style>${fs.readFileSync(path.join(root,'popup.css'),'utf8')}</style>`).replace('<script src="popup.js" defer></script>','');
 await page.setContent(popup);
 await page.evaluate(()=>{window.testState={saved:{},video:{currentSrc:'test.mp4',currentTime:10,duration:300,style:{}},fail:false};window.chrome={storage:{local:{get:async d=>({...d,...testState.saved}),set:async d=>Object.assign(testState.saved,d)}},tabs:{query:async()=>[{id:1,url:'https://www.oneplay.cz/'}]},scripting:{executeScript:async({func,args})=>{if(func.name==='manageAdSkipping')return[{result:{enabled:false,message:''}}];if(testState.fail)throw Error('restricted');const old=document.querySelectorAll.bind(document),computed=window.getComputedStyle;document.querySelectorAll=s=>s==='video'?(testState.video?[testState.video]:[]):old(s);window.getComputedStyle=()=>({display:'block'});try{return[{result:func(...args)}]}finally{document.querySelectorAll=old;window.getComputedStyle=computed}}}}});
 await page.addScriptTag({content:fs.readFileSync(path.join(root,'ad-skip.js'),'utf8')});
 await page.addScriptTag({content:fs.readFileSync(path.join(root,'popup.js'),'utf8')});
 await page.waitForFunction(()=>!document.querySelector('#seconds').disabled);
 assert.equal(await page.locator('#seconds').inputValue(),'60');
 await page.locator('#skip').click();assert.equal(await page.evaluate(()=>testState.video.currentTime),70);
 await page.locator('#plus').click();assert.equal(await page.locator('#seconds').inputValue(),'120');
 await page.locator('#seconds').fill('0');assert(await page.locator('#skip').isDisabled());assert(await page.locator('#minus').isDisabled());
 await page.locator('#seconds').fill('-10');assert.equal(await page.locator('#seconds').inputValue(),'0');
 await page.locator('#seconds').fill('15.9');assert.equal(await page.locator('#seconds').inputValue(),'15');
 await page.evaluate(()=>testState.video.currentTime=295);await page.locator('#skip').click();assert.equal(await page.evaluate(()=>testState.video.currentTime),300);
 await page.evaluate(()=>testState.video=null);await page.locator('#skip').click();assert((await page.locator('#status').textContent()).includes('nebylo nalezeno'));
 await page.evaluate(()=>testState.fail=true);await page.locator('#skip').click();assert((await page.locator('#status').textContent()).includes('nelze rozšíření'));
 await page.locator('#seconds').fill('60');assert.equal(await page.evaluate(()=>testState.saved.seconds),60);
 await page.evaluate(()=>{document.querySelector('#status').textContent='';document.querySelector('#auto-status').textContent='';document.querySelector('#auto-skip').checked=true;document.activeElement.blur()});
 const popupImage=await page.locator('body').screenshot();
 fs.writeFileSync(path.join(root,'store/assets/popup-capture.png'),popupImage);
 const logo=fs.readFileSync(path.join(root,'output/imagegen/logo-60-toolbar.png')).toString('base64');
 await page.setContent(`<html lang="cs"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;width:1280px;height:800px;background:#101827;color:#f8fafc;font-family:Arial,sans-serif;padding:76px} .top{display:flex;align-items:center;gap:20px;font-size:28px;font-weight:bold}.logo{width:72px;height:72px}h1{font-size:54px;line-height:1.1;letter-spacing:-2px;margin:70px 0 24px;max-width:540px}p{font-size:23px;line-height:1.55;color:#becbdd;max-width:500px}.capture{position:absolute;left:670px;top:205px;width:544px;border-radius:12px;box-shadow:0 24px 70px #0008}.tag{font-size:17px;color:#8ba7cf;letter-spacing:2px;margin-top:58px}</style><div class="top"><img class="logo" src="data:image/png;base64,${logo}">Prima Skip Ad</div><h1>Vaše oblíbené pořady bez reklam.</h1><p>Automatické nebo ruční přeskakování reklamních přestávek. Je to Prima!</p><div class="tag">AUTOMATICKY I RUČNĚ</div><img class="capture" src="data:image/png;base64,${popupImage.toString('base64')}"></html>`);
 await page.screenshot({scale:'css',path:path.join(root,'store/assets/screenshot-1280x800.png')});
 await page.setViewportSize({width:440,height:280});
 await page.setContent(`<html><style>body{margin:0;background:#172b57;width:440px;height:280px;display:grid;place-items:center;overflow:hidden}.track{position:absolute;width:350px;height:8px;background:#ffffff26;top:231px;border-radius:4px}.progress{width:230px;height:8px;background:#76a9ff;border-radius:4px}.dot{position:absolute;left:224px;top:-4px;width:16px;height:16px;border-radius:50%;background:#fff}img{width:170px;height:170px;position:absolute;top:30px}</style><img src="data:image/png;base64,${logo}"><div class="track"><div class="progress"></div><div class="dot"></div></div></html>`);
 await page.screenshot({scale:'css',path:path.join(root,'store/assets/promo-440x280.png')});
 assert.deepEqual(errors,[]);
 await browser.close();
 fs.writeFileSync(path.join(root,'store/VALIDATION.md'),'# Validation\n\nThe unchanged popup HTML/CSS/JavaScript was rendered in headless Chrome with a mocked Chrome extension API. The store screenshot uses a capture of that real popup, enlarged within a promotional layout. No playback-success state was fabricated for the screenshot.\n\nPassed: default 60; forward seek; +60; zero disables controls; negative input clamped; decimal input normalized; finite-duration end clamp; missing-video feedback; restricted-page failure feedback; local-save call; no uncaught page errors.\n\nLimitations: Chrome APIs and video objects were simulated. Actual installed-extension permission grants, persistence across browser restarts, and real-site playback remain manual checks. No claim of live Prima-site compatibility testing is made.\n');
 console.log('Popup checks passed; screenshot and promotion rendered.');
})().catch(e=>{console.error(e);process.exit(1)});
